name: Deploy to Kubernetes with Helm

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs only if the build job is successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Decode and set up the kubeconfig
      - name: Decode Kubeconfig and set it up
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config

      # Ensure Minikube is installed
      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      # Start Minikube
      - name: Start Minikube
        run: |
          minikube start --driver=docker

      # Use Minikube's kubectl to configure kubectl for the cluster
      - name: Set Minikube Kubeconfig
        run: |
          minikube kubectl -- get pods

      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Package and deploy your custom Helm chart
      - name: Package and deploy flask-app-chart
        run: |
          # Ensure the chart is packaged and available for deployment
          helm package ./flask-app-chart

          # Install or upgrade the Flask app deployment using your custom chart
          helm upgrade --install flask-app ./flask-app-chart \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/flask-app \
            --set image.tag=${{ github.sha }} \
            --set image.pullPolicy=Always

      # Verify kubectl configuration
      - name: Verify kubectl configuration
        run: |
          kubectl config view
          kubectl get nodes

      # Verify the deployment status
      - name: Verify deployment status
        run: |
          kubectl rollout status deployment/flask-app-deployment
