name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.23.0'  # Specify the version of kubectl you want to use

    - name: Set up kubeconfig
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}  # Store your kubeconfig as a GitHub secret
      run: |
        echo "$KUBE_CONFIG" > ~/.kube/config

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/flask-app-deployment flask-app=${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}
        kubectl rollout status deployment/flask-app-deployment
